FROM nvankaam/codefeedr_build:latest AS build
WORKDIR /root/build


COPY build.sbt .
ADD evaluation/socketgenerator evaluation/socketgenerator/
ADD util/ util/
ADD models/ models/
ADD project/ project/

RUN ["sbt", "project socketgenerator", "assembly"]

FROM openjdk:8-jre AS runtime
workdir /root/app

COPY --from=build /root/build/evaluation/socketgenerator/target/scala-2.11/socketgenerator-assembly-0.1.0-SNAPSHOT.jar socketgenerator.jar

CMD ["java", "-jar", "socketgenerator.jar"]
