#!/usr/bin/env bash
LOCAL_INSTALL_ROOT=/home/nvankaam/afstuderen
LOCAL_CODEFEEDR_SOURCES=$LOCAL_INSTALL_ROOT/codefeedr
LOCAL_ARTIFACT_FOLDER=$LOCAL_CODEFEEDR_SOURCES/target/scala-2.11

TARGET_INSTALL_ROOT=/home/nvankaam/afstuderen
TARGET_CODEFEEDR_SOURCES=$TARGET_INSTALL_ROOT/epoch-alignment
TARGET_CODEFEEDR_EXPERIMENTS=$TARGET_CODEFEEDR_SOURCES/experiments

